language: node_js
script: npm run-script madge && npm run-script mocha && npm run-script coverage
after_script: codeclimate-test-reporter < coverage/lcov.info
node_js:
 - 'node'
 - 'iojs'
 - '5'
 - '4'
 - '0.12'
 - '0.11'
 - '0.10'
sudo: false
addons:
    code_climate:
        repo_token: 6daf1df58d7bd37ca679d2e53201320fe4babe51334fb456dd35673d4a857d37